project:
  type: website

website:
  title: "Bholat"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: courses.qmd
      

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true



